# netlify.toml
[build]
  publish = "."        # publish from root (where index.html lives)
  command = ""         # no build command needed, just serve static files

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
